"""
Import missing CAEN codes (Rev.1, Rev.2, Rev.3) into caen_codes collection.
Parses descriptions from coduricaen.ro data and fills gaps in the database.
"""
import pymongo
import os
import sys

# ── Rev.2 CAEN codes (comprehensive, parsed from rev2.coduricaen.ro) ──
REV2_CODES = {
    "0111": "Cultivarea cerealelor (exclusiv orez), plantelor leguminoase si a plantelor producatoare de seminte oleaginoase",
    "0112": "Cultivarea orezului",
    "0113": "Cultivarea legumelor si a pepenilor, a radacinoaselor si tuberculilor",
    "0114": "Cultivarea trestiei de zahar",
    "0115": "Cultivarea tutunului",
    "0116": "Cultivarea plantelor pentru fibre textile",
    "0119": "Cultivarea altor plante din culturi nepermanente",
    "0121": "Cultivarea strugurilor",
    "0122": "Cultivarea fructelor tropicale si subtropicale",
    "0123": "Cultivarea fructelor citrice",
    "0124": "Cultivarea fructelor semintoase si samburoase",
    "0125": "Cultivarea fructelor arbustilor fructiferi, capsunilor, nuciferilor si a altor pomi fructiferi",
    "0126": "Cultivarea fructelor oleaginoase",
    "0127": "Cultivarea plantelor pentru prepararea bauturilor",
    "0128": "Cultivarea condimentelor, plantelor aromatice, medicinale si a plantelor de uz farmaceutic",
    "0129": "Cultivarea altor plante permanente",
    "0130": "Cultivarea plantelor pentru inmultire",
    "0141": "Cresterea bovinelor de lapte",
    "0142": "Cresterea altor bovine",
    "0143": "Cresterea cailor si a altor cabaline",
    "0144": "Cresterea camilelor si a camelidelor",
    "0145": "Cresterea ovinelor si caprinelor",
    "0146": "Cresterea porcinelor",
    "0147": "Cresterea pasarilor",
    "0149": "Cresterea altor animale",
    "0150": "Activitati in ferme mixte",
    "0161": "Activitati auxiliare pentru productia vegetala",
    "0162": "Activitati auxiliare pentru cresterea animalelor",
    "0163": "Activitati dupa recoltare",
    "0164": "Pregatirea semintelor in vederea insamantarii",
    "0170": "Vanatoare si activitati de servicii anexe vanatorii",
    "0210": "Silvicultura si alte activitati forestiere",
    "0220": "Exploatarea forestiera",
    "0230": "Colectarea plantelor si fructelor din flora spontana",
    "0240": "Activitati de servicii anexe silviculturii",
    "0311": "Pescuitul maritim",
    "0312": "Pescuitul in ape dulci",
    "0321": "Acvacultura maritima",
    "0322": "Acvacultura in ape dulci",
    "0510": "Extractia carbunelui superior",
    "0520": "Extractia carbunelui inferior",
    "0610": "Extractia petrolului brut",
    "0620": "Extractia gazelor naturale",
    "0710": "Extractia minereurilor feroase",
    "0721": "Extractia minereurilor de uraniu si toriu",
    "0729": "Extractia altor minereuri metalifere neferoase",
    "0811": "Extractia pietrei ornamentale si a pietrei pentru constructii",
    "0812": "Extractia pietrisului si nisipului; extractia argilei si caolinului",
    "0891": "Extractia mineralelor pentru industria chimica",
    "0892": "Extractia si aglomerarea turbei",
    "0893": "Extractia sarii",
    "0899": "Alte activitati extractive n.c.a.",
    "0910": "Activitati de servicii anexe extractiei petrolului brut si gazelor naturale",
    "0990": "Activitati de servicii anexe pentru extractia mineralelor",
    "1011": "Prelucrarea si conservarea carnii",
    "1012": "Prelucrarea si conservarea carnii de pasare",
    "1013": "Fabricarea produselor din carne",
    "1020": "Prelucrarea si conservarea pestelui, crustaceelor si molustelor",
    "1031": "Prelucrarea si conservarea cartofilor",
    "1032": "Fabricarea sucurilor de fructe si legume",
    "1039": "Prelucrarea si conservarea fructelor si legumelor n.c.a.",
    "1041": "Fabricarea uleiurilor si grasimilor",
    "1042": "Fabricarea margarinei si a altor produse comestibile similare",
    "1051": "Fabricarea produselor lactate si a branzeturilor",
    "1052": "Fabricarea inghetatei",
    "1061": "Fabricarea produselor de morarit",
    "1062": "Fabricarea amidonului si a produselor din amidon",
    "1071": "Fabricarea painii; fabricarea prajiturilor si a produselor proaspete de patiserie",
    "1072": "Fabricarea biscuitilor si piscoturilor",
    "1073": "Fabricarea macaroanelor, taiteilor si a altor produse fainoase similare",
    "1081": "Fabricarea zaharului",
    "1082": "Fabricarea produselor din cacao, a ciocolatei si a produselor zaharoase",
    "1083": "Prelucrarea ceaiului si cafelei",
    "1084": "Fabricarea condimentelor si ingredientelor",
    "1085": "Fabricarea de mancaruri preparate",
    "1086": "Fabricarea preparatelor alimentare omogenizate si alimentelor dietetice",
    "1089": "Fabricarea altor produse alimentare n.c.a.",
    "1091": "Fabricarea preparatelor pentru hrana animalelor de ferma",
    "1092": "Fabricarea preparatelor pentru hrana animalelor de companie",
    "1101": "Distilarea, rafinarea si mixarea bauturilor alcoolice",
    "1102": "Fabricarea vinurilor din struguri",
    "1103": "Fabricarea cidrului si a altor vinuri din fructe",
    "1104": "Fabricarea altor bauturi nedistilate, obtinute prin fermentare",
    "1105": "Fabricarea berii",
    "1106": "Fabricarea maltului",
    "1107": "Productia de bauturi racoritoare nealcoolice; productia de ape minerale",
    "1200": "Fabricarea produselor din tutun",
    "1310": "Pregatirea fibrelor si filarea fibrelor textile",
    "1320": "Productia de tesaturi",
    "1330": "Finisarea materialelor textile",
    "1391": "Fabricarea de metraje prin tricotare sau crosetare",
    "1392": "Fabricarea de articole confectionate din textile",
    "1393": "Fabricarea de covoare si mochete",
    "1394": "Fabricarea de odgoane, franghii, sfori si plase",
    "1395": "Fabricarea de textile netesute si articole din acestea",
    "1396": "Fabricarea de articole tehnice si industriale din textile",
    "1399": "Fabricarea altor articole textile n.c.a.",
    "1411": "Fabricarea articolelor de imbracaminte din piele",
    "1412": "Fabricarea articolelor de imbracaminte pentru lucru",
    "1413": "Fabricarea altor articole de imbracaminte",
    "1414": "Fabricarea de articole de lenjerie de corp",
    "1419": "Fabricarea altor articole de imbracaminte si accesorii n.c.a.",
    "1420": "Fabricarea articolelor din blana",
    "1431": "Fabricarea prin tricotare sau crosetare a ciorapilor si articolelor de galanterie",
    "1439": "Fabricarea prin tricotare sau crosetare a altor articole de imbracaminte",
    "1511": "Tabacirea si finisarea pieilor; prepararea si vopsirea blanurilor",
    "1512": "Fabricarea articolelor de voiaj si marochinarie",
    "1520": "Fabricarea incaltamintei",
    "1610": "Taierea si rindeluirea lemnului",
    "1621": "Fabricarea de furnire si a panourilor de lemn",
    "1622": "Fabricarea parchetului asamblat in panouri",
    "1623": "Fabricarea altor elemente de dulgherie si tamplarie",
    "1624": "Fabricarea ambalajelor din lemn",
    "1629": "Fabricarea altor produse din lemn",
    "1711": "Fabricarea celulozei",
    "1712": "Fabricarea hartiei si cartonului",
    "1721": "Fabricarea hartiei si cartonului ondulat si a ambalajelor",
    "1722": "Fabricarea produselor de uz gospodaresc si sanitar, din hartie sau carton",
    "1723": "Fabricarea articolelor de papetarie",
    "1724": "Fabricarea tapetului",
    "1729": "Fabricarea altor articole din hartie si carton n.c.a.",
    "1811": "Tiparirea ziarelor",
    "1812": "Alte activitati de tiparire n.c.a.",
    "1813": "Servicii pregatitoare pentru pretiparire",
    "1814": "Legatorie si servicii conexe",
    "1820": "Reproducerea inregistrarilor",
    "1910": "Fabricarea produselor de cocserie",
    "1920": "Fabricarea produselor obtinute din prelucrarea titeiului",
    "2011": "Fabricarea gazelor industriale",
    "2012": "Fabricarea colorantilor si a pigmentilor",
    "2013": "Fabricarea altor produse chimice anorganice, de baza",
    "2014": "Fabricarea altor produse chimice organice, de baza",
    "2015": "Fabricarea ingrasamintelor si produselor azotoase",
    "2016": "Fabricarea materialelor plastice in forme primare",
    "2017": "Fabricarea cauciucului sintetic in forme primare",
    "2020": "Fabricarea pesticidelor si a altor produse agrochimice",
    "2030": "Fabricarea vopselelor, lacurilor, cernelii tipografice si masticurilor",
    "2041": "Fabricarea sapunurilor, detergentilor si a produselor de intretinere",
    "2042": "Fabricarea parfumurilor si a produselor cosmetice",
    "2051": "Fabricarea explozivilor",
    "2052": "Fabricarea cleiurilor",
    "2053": "Fabricarea uleiurilor esentiale",
    "2059": "Fabricarea altor produse chimice n.c.a.",
    "2060": "Fabricarea fibrelor sintetice si artificiale",
    "2110": "Fabricarea produselor farmaceutice de baza",
    "2120": "Fabricarea preparatelor farmaceutice",
    "2211": "Fabricarea anvelopelor si a camerelor de aer",
    "2219": "Fabricarea altor produse din cauciuc",
    "2221": "Fabricarea placilor, foliilor, tuburilor si profilelor din material plastic",
    "2222": "Fabricarea articolelor de ambalaj din material plastic",
    "2223": "Fabricarea articolelor din material plastic pentru constructii",
    "2229": "Fabricarea altor produse din material plastic",
    "2311": "Fabricarea sticlei plate",
    "2312": "Prelucrarea si fasonarea sticlei plate",
    "2313": "Fabricarea articolelor din sticla",
    "2314": "Fabricarea fibrelor din sticla",
    "2319": "Fabricarea de sticlarie tehnica",
    "2320": "Fabricarea de produse refractare",
    "2331": "Fabricarea placilor si dalelor din ceramica",
    "2332": "Fabricarea caramizilor, tiglelor si altor produse pentru constructii",
    "2341": "Fabricarea articolelor ceramice pentru uz gospodaresc si ornamental",
    "2342": "Fabricarea de obiecte sanitare din ceramica",
    "2343": "Fabricarea izolatorilor si pieselor izolante din ceramica",
    "2344": "Fabricarea altor produse ceramice de uz tehnic",
    "2349": "Fabricarea altor produse ceramice n.c.a.",
    "2351": "Fabricarea cimentului",
    "2352": "Fabricarea varului si ipsosului",
    "2361": "Fabricarea produselor din beton pentru constructii",
    "2362": "Fabricarea produselor din ipsos pentru constructii",
    "2363": "Fabricarea betonului",
    "2364": "Fabricarea mortarului",
    "2365": "Fabricarea produselor din azbociment",
    "2369": "Fabricarea altor articole din beton, ciment si ipsos",
    "2370": "Taierea, fasonarea si finisarea pietrei",
    "2391": "Fabricarea de produse abrazive",
    "2399": "Fabricarea altor produse din minerale nemetalice n.c.a.",
    "2410": "Productia de metale feroase sub forme primare si de feroaliaje",
    "2420": "Fabricarea de tuburi, tevi, profile tubulare si accesorii",
    "2431": "Tragere la rece a barelor",
    "2432": "Laminare la rece a benzilor inguste",
    "2433": "Productia de profile obtinute la rece",
    "2434": "Trefilarea firelor la rece",
    "2441": "Productia metalelor pretioase",
    "2442": "Metalurgia aluminiului",
    "2443": "Productia plumbului, zincului si a cositorului",
    "2444": "Metalurgia cuprului",
    "2445": "Productia altor metale neferoase",
    "2446": "Prelucrarea combustibililor nucleari",
    "2451": "Turnarea fontei",
    "2452": "Turnarea otelului",
    "2453": "Turnarea metalelor neferoase usoare",
    "2454": "Turnarea altor metale neferoase",
    "2511": "Fabricarea de constructii metalice",
    "2512": "Fabricarea de usi si ferestre din metal",
    "2521": "Productia de radiatoare si cazane pentru incalzire centrala",
    "2529": "Productia de rezervoare, cisterne si containere metalice",
    "2530": "Productia generatoarelor de abur",
    "2540": "Fabricarea armamentului si munitiei",
    "2550": "Fabricarea produselor metalice obtinute prin deformare plastica",
    "2561": "Tratarea si acoperirea metalelor",
    "2562": "Operatiuni de mecanica generala",
    "2571": "Fabricarea produselor de taiat",
    "2572": "Fabricarea articolelor de feronerie",
    "2573": "Fabricarea uneltelor",
    "2591": "Fabricarea de recipienti si alte produse similare din otel",
    "2592": "Fabricarea ambalajelor usoare din metal",
    "2593": "Fabricarea articolelor din fire metalice",
    "2594": "Fabricarea de suruburi, buloane si alte articole filetate",
    "2599": "Fabricarea altor articole din metal n.c.a.",
    "2611": "Fabricarea subansamblurilor electronice (module)",
    "2612": "Fabricarea altor componente electronice",
    "2620": "Fabricarea calculatoarelor si a echipamentelor periferice",
    "2630": "Fabricarea echipamentelor de comunicatii",
    "2640": "Fabricarea produselor electronice de larg consum",
    "2651": "Fabricarea de instrumente si dispozitive pentru masura, verificare, control",
    "2652": "Productia de ceasuri",
    "2660": "Fabricarea de echipamente pentru radiologie",
    "2670": "Fabricarea de instrumente optice si echipamente fotografice",
    "2680": "Fabricarea suporturilor magnetice si optice",
    "2711": "Fabricarea motoarelor, generatoarelor si transformatoarelor electrice",
    "2712": "Fabricarea aparatelor de distributie si control al electricitatii",
    "2720": "Fabricarea de acumulatori si baterii",
    "2731": "Fabricarea de cabluri cu fibra optica",
    "2732": "Fabricarea altor fire si cabluri electrice si electronice",
    "2733": "Fabricarea dispozitivelor de conexiune",
    "2740": "Fabricarea de echipamente electrice de iluminat",
    "2751": "Fabricarea de aparate electrocasnice",
    "2752": "Fabricarea de echipamente casnice neelectrice",
    "2790": "Fabricarea altor echipamente electrice",
    "2811": "Fabricarea de motoare si turbine",
    "2812": "Fabricarea de echipamente hidraulice si pneumatice",
    "2813": "Fabricarea de alte pompe si compresoare",
    "2814": "Fabricarea de alte articole de robinetarie",
    "2815": "Fabricarea lagarelor, angrenajelor si organelor mecanice de transmisie",
    "2821": "Fabricarea cuptoarelor, furnalelor si arzatoarelor",
    "2822": "Fabricarea echipamentelor de ridicat si manipulat",
    "2823": "Fabricarea masinilor si echipamentelor de birou",
    "2824": "Fabricarea masinilor-unelte portabile actionate electric",
    "2825": "Fabricarea echipamentelor de ventilatie si frigorifice",
    "2829": "Fabricarea altor masini si utilaje de utilizare generala n.c.a.",
    "2830": "Fabricarea masinilor si utilajelor pentru agricultura si exploatari forestiere",
    "2841": "Fabricarea utilajelor si a masinilor-unelte pentru prelucrarea metalului",
    "2849": "Fabricarea altor masini-unelte n.c.a.",
    "2891": "Fabricarea utilajelor pentru metalurgie",
    "2892": "Fabricarea utilajelor pentru extractie si constructii",
    "2893": "Fabricarea utilajelor pentru prelucrarea produselor alimentare",
    "2894": "Fabricarea utilajelor pentru industria textila",
    "2895": "Fabricarea utilajelor pentru industria hartiei si cartonului",
    "2896": "Fabricarea utilajelor pentru prelucrarea maselor plastice si a cauciucului",
    "2899": "Fabricarea altor masini si utilaje specifice n.c.a.",
    "2910": "Fabricarea autovehiculelor de transport rutier",
    "2920": "Productia de caroserii; fabricarea de remorci si semiremorci",
    "2931": "Fabricarea de echipamente electrice si electronice pentru autovehicule",
    "2932": "Fabricarea altor piese si accesorii pentru autovehicule",
    "3011": "Constructia de nave si structuri plutitoare",
    "3012": "Constructia de ambarcatiuni sportive si de agrement",
    "3020": "Fabricarea materialului rulant",
    "3030": "Fabricarea de aeronave si nave spatiale",
    "3040": "Fabricarea vehiculelor militare de lupta",
    "3091": "Fabricarea de motociclete",
    "3092": "Fabricarea de biciclete si vehicule pentru invalizi",
    "3099": "Fabricarea altor mijloace de transport n.c.a.",
    "3101": "Fabricarea de mobila pentru birouri si magazine",
    "3102": "Fabricarea de mobila pentru bucatarii",
    "3103": "Fabricarea de saltele si somiere",
    "3109": "Fabricarea de mobila n.c.a.",
    "3211": "Fabricarea monedelor",
    "3212": "Fabricarea bijuteriilor si articolelor similare",
    "3213": "Fabricarea imitatiilor de bijuterii",
    "3220": "Fabricarea instrumentelor muzicale",
    "3230": "Fabricarea articolelor pentru sport",
    "3240": "Fabricarea jocurilor si jucariilor",
    "3250": "Fabricarea de dispozitive si instrumente medicale si stomatologice",
    "3291": "Fabricarea maturilor si periilor",
    "3299": "Fabricarea altor produse prelucratoare n.c.a.",
    "3311": "Repararea articolelor fabricate din metal",
    "3312": "Repararea masinilor",
    "3313": "Repararea echipamentelor electronice si optice",
    "3314": "Repararea echipamentelor electrice",
    "3315": "Repararea si intretinerea navelor",
    "3316": "Repararea si intretinerea aeronavelor",
    "3317": "Repararea si intretinerea altor echipamente de transport",
    "3319": "Repararea altor echipamente",
    "3320": "Instalarea masinilor si echipamentelor industriale",
    "3511": "Productia de energie electrica",
    "3512": "Transportul energiei electrice",
    "3513": "Distributia energiei electrice",
    "3514": "Comercializarea energiei electrice",
    "3521": "Productia gazelor",
    "3522": "Distributia combustibililor gazosi, prin conducte",
    "3523": "Comercializarea combustibililor gazosi, prin conducte",
    "3530": "Furnizarea de abur si aer conditionat",
    "3600": "Captarea, tratarea si distributia apei",
    "3700": "Colectarea si epurarea apelor uzate",
    "3811": "Colectarea deseurilor nepericuloase",
    "3812": "Colectarea deseurilor periculoase",
    "3821": "Tratarea si eliminarea deseurilor nepericuloase",
    "3822": "Tratarea si eliminarea deseurilor periculoase",
    "3831": "Demontarea masinilor si echipamentelor scoase din uz",
    "3832": "Recuperarea materialelor reciclabile sortate",
    "3900": "Activitati si servicii de decontaminare",
    "4110": "Dezvoltare (promovare) imobiliara",
    "4120": "Lucrari de constructii a cladirilor rezidentiale si nerezidentiale",
    "4211": "Lucrari de constructii a drumurilor si autostrazi",
    "4212": "Lucrari de constructii a cailor ferate",
    "4213": "Constructia de poduri si tuneluri",
    "4221": "Lucrari de constructii a proiectelor utilitare pentru fluide",
    "4222": "Lucrari de constructii a proiectelor utilitare pentru electricitate si telecomunicatii",
    "4291": "Constructii hidrotehnice",
    "4299": "Lucrari de constructii a altor proiecte ingineresti n.c.a.",
    "4311": "Lucrari de demolare a constructiilor",
    "4312": "Lucrari de pregatire a terenului",
    "4313": "Lucrari de foraj si sondaj pentru constructii",
    "4321": "Lucrari de instalatii electrice",
    "4322": "Lucrari de instalatii sanitare, de incalzire si de aer conditionat",
    "4329": "Alte lucrari de instalatii pentru constructii",
    "4331": "Lucrari de ipsoserie",
    "4332": "Lucrari de tamplarie si dulgherie",
    "4333": "Lucrari de pardosire si placare a peretilor",
    "4334": "Lucrari de vopsitorie, zugraveli si montari de geamuri",
    "4339": "Alte lucrari de finisare",
    "4391": "Lucrari de invelitori, sarpante si terase la constructii",
    "4399": "Alte lucrari speciale de constructii n.c.a.",
    "4511": "Comert cu autoturisme si autovehicule usoare",
    "4519": "Comert cu alte autovehicule",
    "4520": "Intretinerea si repararea autovehiculelor",
    "4531": "Comert cu ridicata de piese si accesorii pentru autovehicule",
    "4532": "Comert cu amanuntul de piese si accesorii pentru autovehicule",
    "4540": "Comert cu motociclete, piese si accesorii aferente",
    "4611": "Intermedieri in comertul cu materii prime agricole",
    "4612": "Intermedieri in comertul cu combustibili, minereuri, metale",
    "4613": "Intermedieri in comertul cu material lemnos si materiale de constructii",
    "4614": "Intermedieri in comertul cu masini, echipamente industriale",
    "4615": "Intermedieri in comertul cu mobila, articole de menaj si de fierarie",
    "4616": "Intermedieri in comertul cu textile, confectii din blana, incaltaminte",
    "4617": "Intermedieri in comertul cu produse alimentare, bauturi si tutun",
    "4618": "Intermedieri in comertul specializat in vanzarea produselor cu caracter specific n.c.a.",
    "4619": "Intermedieri in comertul cu produse diverse",
    "4621": "Comert cu ridicata al cerealelor, semintelor, furajelor si tutunului neprelucrat",
    "4622": "Comert cu ridicata al florilor si al plantelor",
    "4623": "Comert cu ridicata al animalelor vii",
    "4624": "Comert cu ridicata al blanurilor, pieilor brute si al pieilor prelucrate",
    "4631": "Comert cu ridicata al fructelor si legumelor",
    "4632": "Comert cu ridicata al carnii si produselor din carne",
    "4633": "Comert cu ridicata al produselor lactate, oualor, uleiurilor si grasimilor",
    "4634": "Comert cu ridicata al bauturilor",
    "4635": "Comert cu ridicata al produselor din tutun",
    "4636": "Comert cu ridicata al zaharului, ciocolatei si produselor zaharoase",
    "4637": "Comert cu ridicata cu cafea, ceai, cacao si condimente",
    "4638": "Comert cu ridicata specializat al altor alimente",
    "4639": "Comert cu ridicata nespecializat de produse alimentare, bauturi si tutun",
    "4641": "Comert cu ridicata al produselor textile",
    "4642": "Comert cu ridicata al imbracamintei si incaltamintei",
    "4643": "Comert cu ridicata al aparatelor electrice de uz gospodaresc",
    "4644": "Comert cu ridicata al produselor din ceramica, sticlarie",
    "4645": "Comert cu ridicata al produselor cosmetice si de parfumerie",
    "4646": "Comert cu ridicata al produselor farmaceutice",
    "4647": "Comert cu ridicata al mobilei, covoarelor si a articolelor de iluminat",
    "4648": "Comert cu ridicata al ceasurilor si bijuteriilor",
    "4649": "Comert cu ridicata al altor bunuri de uz gospodaresc",
    "4651": "Comert cu ridicata al calculatoarelor, echipamentelor periferice si software-ului",
    "4652": "Comert cu ridicata de componente si echipamente electronice si de telecomunicatii",
    "4661": "Comert cu ridicata al masinilor agricole",
    "4662": "Comert cu ridicata al masinilor-unelte",
    "4663": "Comert cu ridicata al masinilor pentru industria miniera si constructii",
    "4664": "Comert cu ridicata al masinilor pentru industria textila",
    "4665": "Comert cu ridicata al mobilei de birou",
    "4666": "Comert cu ridicata al altor masini si echipamente de birou",
    "4669": "Comert cu ridicata al altor masini si echipamente",
    "4671": "Comert cu ridicata al combustibililor solizi, lichizi si gazosi",
    "4672": "Comert cu ridicata al metalelor si minereurilor metalice",
    "4673": "Comert cu ridicata al materialului lemnos si a materialelor de constructii",
    "4674": "Comert cu ridicata al echipamentelor si furniturilor de fierarie",
    "4675": "Comert cu ridicata al produselor chimice",
    "4676": "Comert cu ridicata al altor produse intermediare",
    "4677": "Comert cu ridicata al deseurilor si resturilor",
    "4690": "Comert cu ridicata nespecializat",
    "4711": "Comert cu amanuntul in magazine nespecializate, cu vanzare predominanta de produse alimentare",
    "4719": "Comert cu amanuntul in magazine nespecializate, cu vanzare predominanta de produse nealimentare",
    "4721": "Comert cu amanuntul al fructelor si legumelor proaspete",
    "4722": "Comert cu amanuntul al carnii si al produselor din carne",
    "4723": "Comert cu amanuntul al pestelui, crustaceelor si molustelor",
    "4724": "Comert cu amanuntul al painii, produselor de patiserie si produselor zaharoase",
    "4725": "Comert cu amanuntul al bauturilor",
    "4726": "Comert cu amanuntul al produselor din tutun",
    "4729": "Comert cu amanuntul al altor produse alimentare",
    "4730": "Comert cu amanuntul al carburantilor pentru autovehicule",
    "4741": "Comert cu amanuntul al calculatoarelor, unitatilor periferice si software-ului",
    "4742": "Comert cu amanuntul al echipamentului pentru telecomunicatii",
    "4743": "Comert cu amanuntul al echipamentelor audio/video",
    "4751": "Comert cu amanuntul al textilelor",
    "4752": "Comert cu amanuntul al articolelor de fierarie, al articolelor din sticla",
    "4753": "Comert cu amanuntul al covoarelor, carpetelor, tapetelor",
    "4754": "Comert cu amanuntul al aparatelor electrocasnice",
    "4759": "Comert cu amanuntul al mobilei, al articolelor de iluminat",
    "4761": "Comert cu amanuntul al cartilor",
    "4762": "Comert cu amanuntul al ziarelor si articolelor de papetarie",
    "4763": "Comert cu amanuntul al discurilor si benzilor magnetice cu sau fara inregistrari audio/video",
    "4764": "Comert cu amanuntul al echipamentelor sportive",
    "4765": "Comert cu amanuntul al jocurilor si jucariilor",
    "4771": "Comert cu amanuntul al imbracamintei",
    "4772": "Comert cu amanuntul al incaltamintei si articolelor din piele",
    "4773": "Comert cu amanuntul al produselor farmaceutice",
    "4774": "Comert cu amanuntul al articolelor medicale si ortopedice",
    "4775": "Comert cu amanuntul al produselor cosmetice si de parfumerie",
    "4776": "Comert cu amanuntul al florilor, plantelor si semintelor",
    "4777": "Comert cu amanuntul al ceasurilor si bijuteriilor",
    "4778": "Comert cu amanuntul al altor bunuri noi",
    "4779": "Comert cu amanuntul al bunurilor de ocazie vandute prin magazine",
    "4781": "Comert cu amanuntul al produselor alimentare, bauturilor si tutunului - standuri si piete",
    "4782": "Comert cu amanuntul al textilelor, imbracamintei si incaltamintei - standuri si piete",
    "4789": "Comert cu amanuntul prin standuri, chioscuri si piete al altor produse",
    "4791": "Comert cu amanuntul prin intermediul caselor de comenzi sau prin Internet",
    "4799": "Comert cu amanuntul efectuat in afara magazinelor",
    "4910": "Transporturi interurbane de calatori pe calea ferata",
    "4920": "Transporturi de marfa pe calea ferata",
    "4931": "Transporturi urbane, suburbane si metropolitane de calatori",
    "4932": "Transporturi cu taxiuri",
    "4939": "Alte transporturi terestre de calatori n.c.a.",
    "4941": "Transporturi rutiere de marfuri",
    "4942": "Servicii de mutare",
    "4950": "Transporturi prin conducte",
    "5010": "Transporturi maritime si costiere de pasageri",
    "5020": "Transporturi maritime si costiere de marfuri",
    "5030": "Transportul de pasageri pe cai navigabile interioare",
    "5040": "Transportul de marfuri pe cai navigabile interioare",
    "5110": "Transporturi aeriene de pasageri",
    "5121": "Transporturi aeriene de marfuri",
    "5210": "Depozitari",
    "5221": "Activitati de servicii anexe pentru transporturi terestre",
    "5222": "Activitati de servicii anexe transporturilor pe apa",
    "5223": "Activitati de servicii anexe transporturilor aeriene",
    "5224": "Manipulari",
    "5229": "Alte activitati anexe transporturilor",
    "5310": "Activitati postale desfasurate sub obligativitate de serviciu universal",
    "5320": "Alte activitati postale si de curier",
    "5510": "Hoteluri si alte facilitati de cazare similare",
    "5520": "Facilitati de cazare pentru vacante si perioade de scurta durata",
    "5530": "Parcuri pentru rulote, campinguri si tabere",
    "5590": "Alte servicii de cazare",
    "5610": "Restaurante",
    "5621": "Activitati de alimentatie (catering) pentru evenimente",
    "5629": "Alte servicii de alimentatie n.c.a.",
    "5630": "Baruri si alte activitati de servire a bauturilor",
    "5811": "Activitati de editare a cartilor",
    "5812": "Activitati de editari de ghiduri, compendii, liste de adrese",
    "5813": "Activitati de editare a ziarelor",
    "5814": "Activitati de editare a revistelor si periodicelor",
    "5819": "Alte activitati de editare",
    "5821": "Activitati de editare a jocurilor de calculator",
    "5829": "Activitati de editare a altor produse software",
    "5911": "Activitati de productie cinematografica, video si de programe de televiziune",
    "5912": "Activitati de post-productie cinematografica, video",
    "5913": "Activitati de distributie a filmelor cinematografice, video",
    "5914": "Proiectia de filme cinematografice",
    "5920": "Activitati de realizare a inregistrarilor audio si activitati de editare muzicala",
    "6010": "Activitati de difuzare a programelor de radio",
    "6020": "Activitati de difuzare a programelor de televiziune",
    "6110": "Activitati de telecomunicatii prin retele cu cablu",
    "6120": "Activitati de telecomunicatii prin retele fara cablu",
    "6130": "Activitati de telecomunicatii prin satelit",
    "6190": "Alte activitati de telecomunicatii",
    "6201": "Activitati de realizare a soft-ului la comanda (software orientat client)",
    "6202": "Activitati de consultanta in tehnologia informatiei",
    "6203": "Activitati de management (gestiune si exploatare) a mijloacelor de calcul",
    "6209": "Alte activitati de servicii privind tehnologia informatiei",
    "6311": "Prelucrarea datelor, administrarea paginilor web si activitati conexe",
    "6312": "Activitati ale portalurilor web",
    "6391": "Activitati ale agentiilor de stiri",
    "6399": "Alte activitati de servicii informationale n.c.a.",
    "6411": "Activitati ale bancii centrale (nationale)",
    "6419": "Alte activitati de intermedieri monetare",
    "6420": "Activitati ale holdingurilor",
    "6430": "Fonduri mutuale si alte entitati financiare similare",
    "6491": "Leasing financiar",
    "6492": "Alte activitati de creditare",
    "6499": "Alte intermedieri financiare n.c.a.",
    "6511": "Activitati de asigurari de viata",
    "6512": "Alte activitati de asigurari",
    "6520": "Activitati de reasigurare",
    "6530": "Activitati ale fondurilor de pensii",
    "6611": "Activitati de administrare a pietelor financiare",
    "6612": "Activitati de intermediere a tranzactiilor financiare",
    "6619": "Activitati auxiliare intermedierilor financiare",
    "6621": "Activitati de evaluare a riscului de asigurare si a pagubelor",
    "6622": "Activitati ale agentilor si brokerilor de asigurari",
    "6629": "Alte activitati auxiliare de asigurari si fonduri de pensii",
    "6630": "Activitati de administrare a fondurilor",
    "6810": "Cumpararea si vanzarea de bunuri imobiliare proprii",
    "6820": "Inchirierea si subinchirierea bunurilor imobiliare proprii sau in leasing",
    "6831": "Agentii imobiliare",
    "6832": "Administrarea imobilelor pe baza de comision sau contract",
    "6910": "Activitati juridice",
    "6920": "Activitati de contabilitate si audit financiar; consultanta in domeniul fiscal",
    "7010": "Activitati ale directiilor (centralelor), birourilor administrative centralizate",
    "7021": "Activitati de consultanta in domeniul relatiilor publice si al comunicarii",
    "7022": "Activitati de consultanta pentru afaceri si management",
    "7111": "Activitati de arhitectura",
    "7112": "Activitati de inginerie si consultanta tehnica",
    "7120": "Activitati de testare si analize tehnice",
    "7211": "Cercetare-dezvoltare in biotehnologie",
    "7219": "Cercetare-dezvoltare in alte stiinte naturale si inginerie",
    "7220": "Cercetare-dezvoltare in stiinte sociale si umaniste",
    "7311": "Activitati ale agentiilor de publicitate",
    "7312": "Servicii de reprezentare media",
    "7320": "Activitati de studiere a pietei si de sondare a opiniei publice",
    "7410": "Activitati de design specializat",
    "7420": "Activitati fotografice",
    "7430": "Activitati de traducere scrisa si orala (interpreti)",
    "7490": "Alte activitati profesionale, stiintifice si tehnice n.c.a.",
    "7500": "Activitati veterinare",
    "7711": "Activitati de inchiriere si leasing de autoturisme",
    "7712": "Activitati de inchiriere si leasing de autovehicule rutiere grele",
    "7721": "Activitati de inchiriere si leasing de bunuri recreationale si echipament sportiv",
    "7722": "Inchirierea de casete video si discuri",
    "7729": "Activitati de inchiriere si leasing cu alte bunuri personale si gospodaresti n.c.a.",
    "7731": "Activitati de inchiriere si leasing de masini si echipamente agricole",
    "7732": "Activitati de inchiriere si leasing de masini si echipamente pentru constructii",
    "7733": "Activitati de inchiriere si leasing de masini si echipamente de birou",
    "7734": "Activitati de inchiriere si leasing de masini si echipamente de transport pe apa",
    "7735": "Activitati de inchiriere si leasing de masini si echipamente de transport aerian",
    "7739": "Activitati de inchiriere si leasing-ul altor masini, echipamente si bunuri tangibile",
    "7740": "Leasing de bunuri intangibile (exclusiv financiare)",
    "7810": "Activitati ale agentiilor de plasare a fortei de munca",
    "7820": "Activitati de contractare, pe baze temporare, a personalului",
    "7830": "Alte servicii de furnizare a fortei de munca",
    "7911": "Activitati ale agentiilor turistice",
    "7912": "Activitati ale tur-operatorilor",
    "7990": "Alte servicii de rezervare si asistenta turistica",
    "8010": "Activitati de protectie si garda",
    "8020": "Activitati de servicii privind sistemele de securizare",
    "8030": "Activitati de investigatii",
    "8110": "Activitati de servicii suport combinate",
    "8121": "Activitati generale de curatenie interioara a cladirilor",
    "8122": "Activitati specializate de curatenie",
    "8129": "Alte activitati de curatenie n.c.a.",
    "8130": "Activitati de intretinere peisagistica",
    "8211": "Activitati combinate de secretariat",
    "8219": "Activitati de fotocopiere si alte activitati specializate de secretariat",
    "8220": "Activitati ale centrelor de intermediere telefonica (call center)",
    "8230": "Activitati de organizare a expozitiilor, targurilor si congreselor",
    "8291": "Activitati ale agentiilor de colectare si a birourilor de raportare a creditului",
    "8292": "Activitati de ambalare",
    "8299": "Alte activitati de servicii suport pentru intreprinderi n.c.a.",
    "8411": "Servicii de administratie publica generala",
    "8412": "Reglementarea activitatilor organismelor de ingrijire a sanatatii",
    "8413": "Reglementarea si eficientizarea activitatilor economice",
    "8421": "Activitati de servicii externe",
    "8422": "Activitati de aparare nationala",
    "8423": "Activitati de justitie",
    "8424": "Activitati de ordine publica si de protectie civila",
    "8425": "Activitati de lupta impotriva incendiilor si de prevenire a acestora",
    "8430": "Activitati de protectie sociala obligatorie",
    "8510": "Invatamant prescolar",
    "8520": "Invatamant primar",
    "8531": "Invatamant secundar general",
    "8532": "Invatamant secundar, tehnic sau profesional",
    "8541": "Invatamant superior non-universitar",
    "8542": "Invatamant superior universitar",
    "8551": "Invatamant in domeniul sportiv si recreational",
    "8552": "Invatamant in domeniul cultural",
    "8553": "Scoli de conducere (pilotaj)",
    "8559": "Alte forme de invatamant n.c.a.",
    "8560": "Activitati de servicii suport pentru invatamant",
    "8610": "Activitati de asistenta spitaliceasca",
    "8621": "Activitati de asistenta medicala generala",
    "8622": "Activitati de asistenta medicala specializata",
    "8623": "Activitati de asistenta stomatologica",
    "8690": "Alte activitati referitoare la sanatatea umana",
    "8710": "Activitati ale centrelor de ingrijire medicala",
    "8720": "Activitati ale centrelor de recuperare psihica si de dezintoxicare",
    "8730": "Activitati ale caminelor de batrani",
    "8790": "Alte activitati de asistenta sociala, cu cazare n.c.a.",
    "8810": "Activitati de asistenta sociala, fara cazare, pentru batrani",
    "8891": "Activitati de ingrijire zilnica pentru copii",
    "8899": "Alte activitati de asistenta sociala, fara cazare, n.c.a.",
    "9001": "Activitati de interpretare artistica (spectacole)",
    "9002": "Activitati suport pentru interpretare artistica",
    "9003": "Activitati de creatie artistica",
    "9004": "Activitati de gestionare a salilor de spectacole",
    "9101": "Activitati ale bibliotecilor si arhivelor",
    "9102": "Activitati ale muzeelor",
    "9103": "Gestionarea monumentelor si cladirilor istorice",
    "9104": "Activitati ale gradinilor zoologice, botanice si ale rezervatiilor naturale",
    "9200": "Activitati de jocuri de noroc si pariuri",
    "9311": "Activitati ale bazelor sportive",
    "9312": "Activitati ale cluburilor sportive",
    "9313": "Activitati ale centrelor de fitness",
    "9319": "Alte activitati sportive",
    "9321": "Balciuri si parcuri de distractii",
    "9329": "Alte activitati recreative si distractive n.c.a.",
    "9411": "Activitati ale organizatiilor economice si patronale",
    "9412": "Activitati ale organizatiilor profesionale",
    "9420": "Activitati ale sindicatelor salariatilor",
    "9491": "Activitati ale organizatiilor religioase",
    "9492": "Activitati ale organizatiilor politice",
    "9499": "Activitati ale altor organizatii n.c.a.",
    "9511": "Repararea calculatoarelor si a echipamentelor periferice",
    "9512": "Repararea echipamentelor de comunicatii",
    "9521": "Repararea aparatelor electronice, de uz casnic",
    "9522": "Repararea dispozitivelor de uz gospodaresc",
    "9523": "Repararea incaltamintei si a articolelor din piele",
    "9524": "Repararea mobilei si a furniturilor casnice",
    "9525": "Repararea ceasurilor si a bijuteriilor",
    "9529": "Repararea articolelor de uz personal si gospodaresc n.c.a.",
    "9601": "Spalarea si curatarea articolelor textile si a produselor din blana",
    "9602": "Coafura si alte activitati de infrumusetare",
    "9603": "Activitati de pompe funebre si similare",
    "9604": "Activitati de intretinere corporala",
    "9609": "Alte activitati de servicii n.c.a.",
    "9700": "Activitati ale gospodariilor private in calitate de angajator de personal casnic",
    "9810": "Activitati ale gospodariilor private de producere de bunuri",
    "9820": "Activitati ale gospodariilor private de producere de servicii",
    "9900": "Activitati ale organizatiilor si organismelor extrateritoriale",
}

# ── CAEN 3-digit group codes (Rev.1 style + CAEN group descriptions) ──
GROUP_CODES = {
    "111": "Cultivarea cerealelor si plantelor leguminoase (CAEN Rev.1)",
    "112": "Cultivarea legumelor, horticultura (CAEN Rev.1)",
    "113": "Cultivarea fructelor, nucilor si plantelor pentru bauturi (CAEN Rev.1)",
    "141": "Fabricarea articolelor de imbracaminte",
    "149": "Cresterea altor animale (CAEN Rev.1)",
    "150": "Activitati in ferme mixte (CAEN Rev.1)",
    "521": "Depozitari",
    "522": "Activitati anexe pentru transporturi",
    "620": "Activitati de servicii in tehnologia informatiei",
}

# ── Section mapping ──
SECTION_MAP = {
    "A": "Agricultura, silvicultura si pescuit",
    "B": "Industria extractiva",
    "C": "Industria prelucratoare",
    "D": "Productia si furnizarea de energie electrica si termica, gaze, apa calda si aer conditionat",
    "E": "Distributia apei; salubritate, gestionarea deseurilor, activitati de decontaminare",
    "F": "Constructii",
    "G": "Comert cu ridicata si cu amanuntul; repararea autovehiculelor si motocicletelor",
    "H": "Transport si depozitare",
    "I": "Hoteluri si restaurante",
    "J": "Informatii si comunicatii",
    "K": "Intermedieri financiare si asigurari",
    "L": "Tranzactii imobiliare",
    "M": "Activitati profesionale, stiintifice si tehnice",
    "N": "Activitati de servicii administrative si activitati de servicii suport",
    "O": "Administratie publica si aparare; asigurari sociale din sistemul public",
    "P": "Invatamant",
    "Q": "Sanatate si asistenta sociala",
    "R": "Activitati de spectacole, culturale si recreative",
    "S": "Alte activitati de servicii",
    "T": "Activitati ale gospodariilor private",
    "U": "Activitati ale organizatiilor si organismelor extrateritoriale",
}

def _code_to_section_letter(code):
    try:
        d = int(code[:2])
    except (ValueError, TypeError):
        return ""
    if 1 <= d <= 3: return "A"
    if 5 <= d <= 9: return "B"
    if 10 <= d <= 33: return "C"
    if d == 35: return "D"
    if 36 <= d <= 39: return "E"
    if 41 <= d <= 43: return "F"
    if 45 <= d <= 47: return "G"
    if 49 <= d <= 53: return "H"
    if 55 <= d <= 56: return "I"
    if 58 <= d <= 63: return "J"
    if 64 <= d <= 66: return "K"
    if d == 68: return "L"
    if 69 <= d <= 75: return "M"
    if 77 <= d <= 82: return "N"
    if d == 84: return "O"
    if d == 85: return "P"
    if 86 <= d <= 88: return "Q"
    if 90 <= d <= 93: return "R"
    if 94 <= d <= 96: return "S"
    if 97 <= d <= 98: return "T"
    if d == 99: return "U"
    return ""


def run_import():
    mongo_url = os.environ.get("MONGO_URL")
    if not mongo_url:
        print("ERROR: MONGO_URL not set")
        sys.exit(1)

    client = pymongo.MongoClient(mongo_url)
    db = client["mfirme_local"]

    existing = set()
    for doc in db.caen_codes.find({}, {"_id": 0, "cod": 1}):
        existing.add(doc["cod"])
    print(f"Existing CAEN codes in DB: {len(existing)}")

    # Get all distinct CAEN codes used by firme
    pipeline = [
        {"$match": {"anaf_cod_caen": {"$exists": True, "$ne": None, "$ne": ""}}},
        {"$group": {"_id": "$anaf_cod_caen", "count": {"$sum": 1}}},
        {"$sort": {"count": -1}},
    ]
    firme_caen = {}
    for doc in db.firme.aggregate(pipeline, allowDiskUse=True):
        code = str(doc["_id"])
        firme_caen[code] = doc["count"]

    missing = {k: v for k, v in firme_caen.items() if k not in existing}
    print(f"Missing CAEN codes: {len(missing)}")

    # Build lookup
    all_codes = {}
    all_codes.update(REV2_CODES)
    all_codes.update(GROUP_CODES)

    inserted = 0
    not_found_codes = []

    for code, firm_count in sorted(missing.items(), key=lambda x: -x[1]):
        if code in ("None", "0", "", "null"):
            continue

        description = all_codes.get(code, "")
        if not description and len(code) == 3:
            description = all_codes.get("0" + code, "")
        if not description and len(code) == 4 and code.startswith("0"):
            description = all_codes.get(code[1:], "")

        if not description:
            not_found_codes.append((code, firm_count))
            description = f"Cod CAEN {code}"

        section_letter = _code_to_section_letter(code)
        section_name = SECTION_MAP.get(section_letter, "")

        doc = {
            "cod": code,
            "name": description,
            "description": description,
            "denumire": description,
            "section": code[:2] if len(code) >= 2 else code,
            "sectiune": section_letter,
            "sectiune_denumire": section_name,
        }

        db.caen_codes.update_one({"cod": code}, {"$set": doc}, upsert=True)
        inserted += 1

    # Update existing codes that lack sectiune/denumire fields
    updated = 0
    for doc in db.caen_codes.find({"sectiune": {"$exists": False}}, {"_id": 0, "cod": 1, "name": 1}):
        code = doc["cod"]
        section_letter = _code_to_section_letter(code)
        section_name = SECTION_MAP.get(section_letter, "")
        db.caen_codes.update_one(
            {"cod": code},
            {"$set": {"sectiune": section_letter, "sectiune_denumire": section_name, "denumire": doc.get("name", "")}},
        )
        updated += 1

    final_count = db.caen_codes.count_documents({})
    print(f"\n=== IMPORT COMPLETE ===")
    print(f"Inserted/updated: {inserted}")
    print(f"Updated existing (added sectiune): {updated}")
    print(f"Total caen_codes now: {final_count}")
    if not_found_codes:
        print(f"\nCodes without known description ({len(not_found_codes)}):")
        for code, count in not_found_codes[:20]:
            print(f"  {code}: {count} firme")

    print(f"\n=== VERIFICATION ===")
    for code in ["5211", "4100", "111", "113", "149", "150", "4521", "4933", "5262", "6210", "4712", "7020"]:
        d = db.caen_codes.find_one({"cod": code}, {"_id": 0, "cod": 1, "denumire": 1})
        if d:
            print(f"  OK  {d['cod']}: {d.get('denumire', 'N/A')[:70]}")
        else:
            print(f"  MISSING  {code}")

    client.close()


if __name__ == "__main__":
    run_import()
